<h1 style = "text-align : center ; " > Numpy </h1>

## What is Numpy ? 

## Why Numpy ?

## Data Science Packages: 


Packages built on top of numpy: <br> 
- Pandas
- Pyspark 
- Polars
- Matplotlib
- Plotly
- Dask 
- Seaborn 
- OpenCV 
- Mito 
- Pandas Profilling

In [1]:
import math 
print(math.pi)
# int x = 4; c++ 4 byte 
# x = 4 : 16 python 

3.141592653589793


In [2]:
import numpy as np
import pandas as pd 

/opt/miniconda3/envs/base_new/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/miniconda3/envs/base_new/lib/python3.9/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


### Numpy Data Types
Numpy has the following data types: 
- ```int```
- ```float```
- ```complex```
- ```bool```
- ```string```
- ```unicode```
- ```object```

The numeric data types have various precisions like 32-bit or 64-bit. 

Numpy data types can be represented using either __Type__ or __Type Code__

In [3]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

dtypes

,Type,Type Code
0,int8,i1
1,uint8,u1
2,int16,i2
3,uint16,u2
4,int or int32,i4 or i
5,uint32,u4
6,int64,i8
7,uint64,u8
8,float16,f2
9,float32,f4 or f


In [ ]:
int8 : integer in 8 bit ( 1 byte ) 
    0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 1
    0 0 0 0 0 0 1 0
    0 0 0 0 0 0 1 1
    0 0 0 0 0 1 0 0
    1 1 1 1 1 1 1 1 
int16: 
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
    0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0

max value in int8 : 
    
positive:  0 1 1 1 1 1 1 1
negative:  1 1 1 1 1 1 1 1
        
int8 vs uint8 : 
    int : 0 positive 0 0 0 0 0 0 0 0
              one:   0 0 0 0 0 0 0 1
        : 1 negative 0 0 0 0 0 0 0
            - one:   1 0 0 0 0 0 0 1
    uint: "doesn't support negative" 
                     0 0 0 0 0 0 0 0 
max number int8 :  -128 to 127
max number uint8:  0 to 255
max number int16 :  -32768 to 32767
max number uint16:  0 to 65535

    int8 --> 2^7 - 1 : 127
    int16 --> 2^15 - 1 : 32767 
    
x = 140 , int8 ? no , uint8 , int16 

1 byte = 8 bit : 0 0 0 0 0 0 0 0 
2 byte = 16 bit  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
4 byte = 32 bit  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
8 byte = 64 bit  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [1]:
x = 3.9999999999999999
x

4.0

In [4]:
3.66666666666666666666666

3.6666666666666665

In [5]:
1.1 - 0.9

0.20000000000000007

In [8]:
round(1.1 - .9 , 1)

0.2

In [9]:
round(1.1 - .9)

0

In [ ]:
import numpy as np 
from numpy import * 
from numpy import array , mean 

In [1]:
import numpy as np 

In [1]:
from numpy import * 

In [2]:
from numpy import array , mean 

In [3]:
%whos 

Variable   Type                          Data/Info
--------------------------------------------------
array      builtin_function_or_method    <built-in function array>
mean       function                      <function mean at 0x111798b80>


In [4]:
from numpy import array as np_array 

In [6]:
my_array = np_array([1,2,3])
my_array , type (my_array)

(array([1, 2, 3]), numpy.ndarray)

**The Difference between np and * :**

In [7]:
# import numpy as np 
# -> np.function_name

# from numpy import * 
# function_name

# from numpy import x 
# x()

# from numpy import x as abc
# abc()

# Example case 1: 
# import numpy as np : 
# create array : my_arr = np.array([])

# Example case 2: 
# from numpy import * : 
# create array : my_arr = array([])

### Creating Arrays 

In [9]:
import numpy as np 

In [10]:
my_array = np.array([1,2,3])
type(my_array)

numpy.ndarray

In [11]:
my_array

array([1, 2, 3])

In [12]:
my_array.dtype 

dtype('int64')

In [14]:
arr = np.array([1,2,3], dtype ='f4')
arr

array([1., 2., 3.], dtype=float32)

In [15]:
# Identical to the above
arr = np.array([1,2,3], dtype= 'float32' )
arr.dtype

dtype('float32')

In [16]:
arr = np.array([1,2,3])
arr.dtype , arr.nbytes

(dtype('int64'), 24)

In [17]:
arr = np.array([1,2,3], dtype = 'int8')
arr.dtype , arr.nbytes

(dtype('int8'), 3)

In [13]:
arr = np.array([7,6,8], dtype = 'int16')
arr.dtype , arr.nbytes

(dtype('int16'), 6)

In [12]:
arr = np.array([1,2,"Ahmed"], dtype='float32')
arr.dtype

for i in arr:
    print(type(i))

ValueError: could not convert string to float: 'Ahmed'

In [18]:
arr = np.array([1,2,"Ahmed"])
arr.dtype

dtype('<U21')

In [19]:
arr[0], arr[1] , arr[2]

('1', '2', 'Ahmed')

In [20]:
arr.nbytes 

252

In [22]:
arr = np.array([1,2,2.1])
arr.dtype, arr 

(dtype('float64'), array([1. , 2. , 2.1]))

In [23]:
arr = np.array([1,2.1, True])
arr.dtype

dtype('float64')

In [24]:
arr[-1]

1.0

In [25]:
arr = np.array([1,2,True])
arr.dtype

dtype('int64')

In [26]:
arr[-1]

1

In [27]:
arr = np.array([1,2,"3.4"], dtype='float32')

for i in arr:
    print(i)
    
print(arr[2]+3)

1.0
2.0
3.4
6.400000095367432


In [28]:
arr = np.array([1,2,"3.4"])
arr.dtype

dtype('<U21')

In [29]:
arr = np.array(["1","2","3"], dtype='int')
print(arr.dtype)

for i in arr:
    print(i)

int64
1
2
3


In [24]:
arr = np.array([1,2,"3"], dtype='float32')
arr.dtype

for i in arr:
    print(type(i))
arr

<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>


array([1., 2., 3.], dtype=float32)

In [25]:
arr = np.array([1.1,2.2,"3"], dtype='int')
print(arr.dtype)

for i in arr:
    print(i)

int64
1
2
3


In [28]:
arr = np.array([1.1,2.2,"3"])
print(arr.dtype)
print(arr.nbytes)
for i in arr:
    print(i) , print(type(i))

<U32
384
1.1
<class 'numpy.str_'>
2.2
<class 'numpy.str_'>
3
<class 'numpy.str_'>


In [29]:
# arr = np.array([ ] , dtype = )

In [31]:
arr = np.array([1,2,3], dtype='int16') # 16 / 8 = 2 ( 2 bytes )
print('Original Data Type: ' + str(arr.dtype))
print(arr.nbytes)

print()

arr = arr.astype(np.float32) # convert arr type from int16 --> float32 ( 8 bytes )
print('Data Type After Conversion: ' + str(arr.dtype))
print(arr.nbytes)
arr

Original Data Type: int16
6

Data Type After Conversion: float32
12


array([1., 2., 3.], dtype=float32)

In [26]:
# note
3. 

3.0

In [30]:
arr = np.array([126,127,129], dtype='int16')
print('array before type conversion: ' + str(arr))

arr = arr.astype('int8')
print('array after type conversion: ' + str(arr))

array before type conversion: [126 127 129]
array after type conversion: [ 126  127 -127]


In [31]:
arr = np.array([126,127,129], dtype='int32')
print('np array before type conversion: ' + str(arr))

arr = arr.astype('int16')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 129]
np array after type conversion: [126 127 129]


In [28]:
arr = np.array([126,127,230], dtype='int16')
print('array before : ' + str(arr))
arr = arr.astype('int8')
print('array after: ' + str(arr))

array before : [126 127 230]
array after: [126 127 -26]


In [32]:
# note : don't forget to check the max number in array before conversion 
arr.max()

129

In [27]:
max(arr)

127

In [34]:
# create array : np.array([ , , , ], dtype = )
# check array data type : array.dtype
# check array number of bytes : array.nbytes
# convert array : new_array = old_array.astype(newtype)
# check max value in array : araay.max() , max(array)

### String Array

In [36]:
s = np.array(['Ahmed', 'Ali'], dtype='S3')
print(s)

s = np.array(['minimum', 'maximum'], dtype='U3')
print(s)

[b'Ahm' b'Ali']
['min' 'max']


In [35]:
arr = np.array(['a', 'ab', 'abc'], dtype = np.string_ )
print(arr.dtype) 


arr = np.array(['a', 'abc', 'abcd'], dtype=np.unicode_)
print('The data type is ' + str(arr.dtype) + ' because the longest unicode in the array is "abcd" and its length is 4.')

|S3
The data type is <U4 because the longest unicode in the array is "abcd" and its length is 4.


In [ ]:
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print(arr.dtype)

arr[0] = "Ahmed Hafez"

print(arr)
print(arr.dtype)


|S3
[b'Ahm' b'ab' b'abc']
|S3


In [37]:
bool_arr = np.array([True, False])
bool_arr.dtype

dtype('bool')

In [38]:
bool_arr.nbytes

2

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` 
- ```iterator```


In [40]:
mylist = [1,2,3,4,5]
print("mylist type", type(mylist)) 


arr = np.array(mylist)
print(arr)

l = [1,2,3,4,5]
print(l)

print(type(l))
print(type(arr))
print(arr.dtype)

mylist type <class 'list'>
[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
int64


In [41]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [42]:
arr = np.array(range(10,21,2) )
print(arr)
print(arr.dtype)

arr = arr.astype(np.int8)
arr.dtype

[10 12 14 16 18 20]
int64


dtype('int8')

### Create an array with specified data type

In [40]:
arr = np.array([  [1,2,3], [4,5,6]  ], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))
print(arr.shape)

[[1 2 3]
 [4 5 6]]
Data Type: int16
(2, 3)


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [43]:
# np.arange(start, stop, step)
arr = np.arange(0, 21, 3)  
print(arr)
print(type(arr))

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>


In [53]:
arr = np.random.rand(3,4)
print(arr)

[[0.97669698 0.09637428 0.8846457  0.92293093]
 [0.03360978 0.05553272 0.06159644 0.31256256]
 [0.99788149 0.83112154 0.38042912 0.06267926]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [54]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.int16)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0 0]
 [0 0]
 [0 0]]
Data Type: int16


In [56]:
arr = np.array([[1,2],
                [3,4],
                [5,6]],
               dtype=np.int16)

zeros = np.zeros_like(arr)

print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0 0]
 [0 0]
 [0 0]]
Data Type: int16


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [57]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [58]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int64


In [59]:
arr = np.array([[1,2], [3,4],[5,2147483647]])
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1]
 [1 1]
 [1 1]]
Data Type: int64


In [52]:
arr = np.array([[1,2], [3,4],[5,2147483647]], dtype = "float32")
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
Data Type: float32


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [62]:
empty = np.empty((5,5))
print(empty)
print(empty.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [63]:
newarr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(newarr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
Data Type: int64


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [64]:
full = np.full((4,4), 6)
print(full)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [65]:
arr = np.array([[1,2], [3,4.4]])
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


In [56]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [66]:
identity_matrix = np.eye(4)
#identity_matrix = identity_matrix.astype(int)
print(identity_matrix)
print(type(identity_matrix))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [41]:
identity_matrix = np.eye(3).astype(int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [67]:
identity_matrix = np.identity(5)
print(identity_matrix)
print(type(identity_matrix))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [68]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x113829250
byteorder:  little
byteswap:  False
type: int64
None


### inspect the data type of an array

In [70]:
print(arr.dtype)

int64


### inspect the dimension of an array

In [71]:
print(arr.shape)

(2, 3)


### inspect length of an array ( number of rows ) 

In [72]:
print(len(arr)) # print number of rows 

2


### inspect the number of dimensions of an array

In [73]:
print(arr.ndim)

2


### inspect the total number of elements in an array

In [74]:
print(arr.size)

6


### inspect the number of bytes of each element in an array ( byte ) 

In [75]:
print(arr.itemsize)  # bytes

8


### inspect the memory size of an array (in byte)

In [76]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


In [77]:
print((arr.nbytes) * 8 ) # bits

384


In [50]:
my_3D_array = np.array(
    [
        [ [2,3] , [3,2] ] , [ [1,1] , [1,1]  ]
    ]
)
my_3D_array.shape 

(2, 2, 2)

In [51]:
_3d_array = np.array([  [[2,3] , [4,5]   ] ,[   [4,3],[2,8]   ]     ])
print(_3d_array.shape)
print(_3d_array.ndim)

(2, 2, 2)
3


In [53]:
_3d_array

array([[[2, 3],
        [4, 5]],

       [[4, 3],
        [2, 8]]])

In [78]:
_4d_array = np.array([ [ [ [1,2] , [3,4] ] , [  [5,6],[7,8] ]  ] , [  [ [9,10] , [11, 12] ], [ [13,14] , [15,16]]  ]   ] )
print(_4d_array.shape)
_4d_array.ndim

(2, 2, 2, 2)


4

In [54]:
_4d_array

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

#### Random numbers

In [80]:
np.random.rand()

0.29094599307685876

In [90]:
np.random.rand(3)

array([0.85715425, 0.16508662, 0.63233401])

In [91]:
np.random.seed(11)
np.random.rand(4)

array([0.18026969, 0.01947524, 0.46321853, 0.72493393])

In [92]:
np.random.seed(24)
np.random.rand(4)

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 ])

In [93]:
np.random.seed(2)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

In [97]:
np.random.seed()
np.random.rand(3)

array([0.37808679, 0.03153888, 0.04860618])

In [100]:
rs = np.random.RandomState(23)
rs.rand(10)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009])

In [78]:
rs = np.random.RandomState(321)
rs.rand(3)

array([0.88594794, 0.07791236, 0.97964616])

### generate a random sample from interval [0, 1) in a given shape

In [44]:
# generate a random scalar
print(np.random.rand())  # from zero to one    

0.42020360458772743


In [49]:
# generate a random scalar
print(np.random.rand() * 10)      

8.507950893767788


In [50]:
# generate a random scalar
print(int(np.random.rand() * 10))      

7


In [51]:
# generate a random scalar
print(np.random.rand() * 100)

10.873607186897495


In [52]:
# generate a 1-D array
print(np.random.rand(10) )
print(type(np.random.rand(10)))

[0.89390417 0.85715425 0.16508662 0.63233401 0.02048361 0.11673727
 0.31636731 0.15791231 0.75897959 0.81827536]
<class 'numpy.ndarray'>


In [105]:
np.random.choice([1,2,4,5,6], 2)

array([2, 2])

In [114]:
np.random.choice(["Ahmed", "Ali", "Essam", "Bale", "Mohamed"], 2)

array(['Bale', 'Bale'], dtype='<U7')

In [69]:
np.random.choice(["Ahmed", "Ali", "Essam", "Bale", "Mohamed"], 2, replace = False ) # element can't be choosen twice

array(['Mohamed', 'Ahmed'], dtype='<U7')

In [115]:
# generate a 2D array
print(np.random.rand(3,3))          

[[0.59665867 0.58935931 0.77748065]
 [0.03886916 0.43360512 0.703532  ]
 [0.37080311 0.12537561 0.05264449]]


In [116]:
# generate a 3D array
print(np.random.rand(3,3,3))

[[[0.67601046 0.64151747 0.87491156]
  [0.05462601 0.20665868 0.64111635]
  [0.07388135 0.18925143 0.6170997 ]]

 [[0.41499975 0.9322577  0.00539241]
  [0.70112768 0.65975278 0.39385797]
  [0.06431294 0.23730299 0.24233879]]

 [[0.59839749 0.32840741 0.23597007]
  [0.4689806  0.32664536 0.65392863]
  [0.40249955 0.13910619 0.80091828]]]


In [117]:
# generate a 4-D array
print(np.random.rand(3,3,3,3))          

[[[[0.75735321 0.47525252 0.56592958]
   [0.8557174  0.36356341 0.41826284]
   [0.88386944 0.91974406 0.09114547]]

  [[0.35847258 0.28962801 0.89689079]
   [0.91074613 0.28822285 0.12175806]
   [0.23154869 0.2068688  0.79268324]]

  [[0.57558607 0.27195193 0.35776939]
   [0.81742698 0.61866839 0.27951821]
   [0.37085193 0.07080185 0.32128368]]]


 [[[0.291372   0.12002945 0.98566921]
   [0.84046469 0.22067557 0.46205978]
   [0.58016635 0.17544094 0.16392113]]

  [[0.6134852  0.08592482 0.05721752]
   [0.84716468 0.47492315 0.45951894]
   [0.76253358 0.98758014 0.7764969 ]]

  [[0.2436827  0.55137666 0.55804487]
   [0.51161357 0.63009144 0.2934951 ]
   [0.60396308 0.69048268 0.52026088]]]


 [[[0.94518728 0.18430836 0.43711042]
   [0.95831482 0.8504822  0.00377392]
   [0.69558241 0.31104858 0.03070798]]

  [[0.95777229 0.78707491 0.36238482]
   [0.09338762 0.87418476 0.68940478]
   [0.03405836 0.30488959 0.94669572]]

  [[0.18939334 0.69481741 0.75118558]
   [0.18415283 0.51197394 0.33

### generate an array of random integers in a given interval [low, high)

In [120]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[1 6 8]


In [122]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 100, 5, 'i8'))

[99 68 88 29 86]


In [124]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 100, 1, 'i8'))

[50]


In [125]:
def generate_random_integars ( start , end, n) : 
    return (np.random.randint(start, end, n, 'i8'))

In [126]:
generate_random_integars(1, 7, 2) 

array([4, 5])

In [127]:
def generate_random_integartes_n_from_to ( n , fromm  , to ) : 
    return (np.random.randint(fromm , to , n, 'i8'))

In [128]:
generate_random_integartes_n_from_to(3, 5, 200)

array([162, 186, 174])

### generate a random sample from a given 1-D array

In [109]:
import numpy as np 

In [110]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.3, 0.6]))

[2 1 2 2 1 2 1 1 1 1]


### shuffle an array in place

In [129]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [137]:
np.random.shuffle(arr)
print(arr)

[1 0 9 6 4 7 5 8 2 3]


### generate a permutation of an array

In [138]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [4 3 7 1 0 9 8 6 2 5]


### Addition , Subtraction and more... 

In [143]:
arr = np.random.rand(5,5)
arr

array([[0.28930755, 0.73780307, 0.15087961, 0.968783  , 0.0133926 ],
       [0.18103882, 0.90186946, 0.61394239, 0.01045742, 0.80791797],
       [0.51381148, 0.38391667, 0.56561182, 0.19547195, 0.18498457],
       [0.67321465, 0.93816298, 0.2249249 , 0.92069915, 0.13741822],
       [0.1001526 , 0.60750893, 0.12675375, 0.03410993, 0.3040398 ]])

### element-wise addition, subtraction, multiplication and division

In [124]:
print(arr + 10)
print()
print(arr - 10)
print()
print(arr * 10)
print()
print(arr / 10)

[[10.2587931  10.52282832 10.19220549 10.51717191 10.1422774 ]
 [10.40375927 10.01846341 10.49852598 10.15336825 10.14940179]
 [10.73024099 10.68066128 10.07361874 10.70799054 10.12209955]
 [10.19146487 10.70069123 10.61835847 10.64026753 10.86702878]
 [10.19243299 10.38592757 10.70456194 10.72686329 10.55251105]]

[[-9.7412069  -9.47717168 -9.80779451 -9.48282809 -9.8577226 ]
 [-9.59624073 -9.98153659 -9.50147402 -9.84663175 -9.85059821]
 [-9.26975901 -9.31933872 -9.92638126 -9.29200946 -9.87790045]
 [-9.80853513 -9.29930877 -9.38164153 -9.35973247 -9.13297122]
 [-9.80756701 -9.61407243 -9.29543806 -9.27313671 -9.44748895]]

[[2.58793103 5.22828323 1.92205489 5.17171914 1.42277401]
 [4.03759272 0.18463412 4.98525975 1.53368254 1.49401792]
 [7.30240994 6.80661283 0.73618738 7.07990536 1.22099549]
 [1.91464872 7.00691231 6.18358473 6.40267529 8.67028776]
 [1.92432988 3.85927565 7.04561941 7.26863288 5.52511053]]

[[0.02587931 0.05228283 0.01922055 0.05171719 0.01422774]
 [0.04037593 0.0

In [127]:
arr 

array([[0.06751964, 0.22251326, 0.16313935, 0.24005031, 0.36219198],
       [0.58581716, 0.53615008, 0.33473192, 0.71702016, 0.18242888],
       [0.19576426, 0.47522641, 0.30719473, 0.20317147, 0.76342927],
       [0.74407549, 0.54460283, 0.85249888, 0.96629436, 0.16694411],
       [0.47269629, 0.49725255, 0.08222204, 0.32851749, 0.57946283]])

In [139]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
x = np.add(arr1, [8,9,10], out = arr1)
print(arr1)

np.subtract(arr1, [2,1,12], out = arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out = arr1)
print(arr1)

[ 9 11 13]
[ 7 10  1]
[ 7 20  3]


In [126]:
result = np.divide(arr1 , [1,3,4] ) 
result  

array([7.        , 6.66666667, 0.75      ])

### element-wise exponentiation

In [140]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
print(np.exp(arr))

[[1.29536577 1.6867917  1.21191953 1.67727745 1.15289642]
 [1.49744343 1.01863491 1.64629281 1.16575419 1.16113943]
 [2.07558075 1.97518346 1.07639634 2.02990813 1.12986657]
 [1.21102229 2.01514516 1.85587906 1.89698831 2.37982933]
 [1.21219527 1.47097812 2.02296031 2.06858188 1.73761078]]


### element-wise logorithm

In [144]:
# natural log ( base e )
print(np.log(arr)) 

[[-1.24026498 -0.30407834 -1.89127302 -0.03171464 -4.31305333]
 [-1.70904381 -0.1032855  -0.48785417 -4.56044316 -0.21329475]
 [-0.66589885 -0.95732977 -0.56984727 -1.63233837 -1.68748285]
 [-0.39569105 -0.0638316  -1.49198871 -0.08262195 -1.98472631]
 [-2.30106029 -0.4983884  -2.06550904 -3.37816665 -1.19059666]]


In [130]:
# base 2
print(np.log2(arr))     

[[-1.95012893 -0.9355908  -2.37927855 -0.95128417 -2.81322157]
 [-1.3084327  -5.759187   -1.00425942 -2.70492821 -2.74273064]
 [-0.45355543 -0.55499104 -3.76378317 -0.49819802 -3.03387022]
 [-2.38484837 -0.51314925 -0.69348466 -0.64325325 -0.20584822]
 [-2.37757196 -1.373598   -0.50520155 -0.46024405 -0.85592477]]


In [131]:
# base 10
print(np.log10(arr))    

[[-0.5870473  -0.28164089 -0.71623421 -0.28636507 -0.84686408]
 [-0.39387749 -1.73368804 -0.30231221 -0.81426453 -0.82564419]
 [-0.13653379 -0.16706895 -1.13301163 -0.14997255 -0.91328594]
 [-0.71791089 -0.15447332 -0.20875968 -0.19363852 -0.06196649]
 [-0.71572048 -0.4134942  -0.15208082 -0.13854727 -0.25765903]]


### element-wise square root

In [145]:
arr 

array([[0.28930755, 0.73780307, 0.15087961, 0.968783  , 0.0133926 ],
       [0.18103882, 0.90186946, 0.61394239, 0.01045742, 0.80791797],
       [0.51381148, 0.38391667, 0.56561182, 0.19547195, 0.18498457],
       [0.67321465, 0.93816298, 0.2249249 , 0.92069915, 0.13741822],
       [0.1001526 , 0.60750893, 0.12675375, 0.03410993, 0.3040398 ]])

In [146]:
print(np.sqrt(arr))

[[0.53787317 0.85895464 0.38843225 0.98426775 0.11572638]
 [0.42548657 0.94966808 0.78354476 0.10226155 0.89884257]
 [0.71680645 0.61961009 0.75207169 0.4421221  0.43009833]
 [0.82049659 0.96858814 0.47426248 0.95953069 0.37069963]
 [0.31646895 0.77942859 0.35602493 0.18468875 0.55139804]]


### element-wise sine and cosine

In [134]:
arr 

array([[0.2587931 , 0.52282832, 0.19220549, 0.51717191, 0.1422774 ],
       [0.40375927, 0.01846341, 0.49852598, 0.15336825, 0.14940179],
       [0.73024099, 0.68066128, 0.07361874, 0.70799054, 0.12209955],
       [0.19146487, 0.70069123, 0.61835847, 0.64026753, 0.86702878],
       [0.19243299, 0.38592757, 0.70456194, 0.72686329, 0.55251105]])

In [147]:
print(np.sin(arr))

[[0.28528862 0.67266392 0.15030781 0.82419713 0.01339219]
 [0.18005151 0.78448761 0.57609438 0.01045723 0.72285005]
 [0.49150014 0.37455488 0.53593245 0.19422952 0.18393137]
 [0.62350249 0.80647328 0.22303315 0.79602499 0.13698613]
 [0.09998525 0.57082389 0.12641461 0.03410332 0.29937716]]


In [148]:
print(np.cos(arr))

[[0.95844165 0.73994814 0.98863925 0.566303   0.99991032]
 [0.98365718 0.62014449 0.81738318 0.99994532 0.69100493]
 [0.87087749 0.92720474 0.84426086 0.98095611 0.98293909]
 [0.78182136 0.59127053 0.97481086 0.60526376 0.99057297]
 [0.99498892 0.82107252 0.99197749 0.99941831 0.95413485]]


In [149]:
print(np.tan(arr))

[[0.29765883 0.909069   0.15203504 1.45539954 0.0133934 ]
 [0.18304295 1.2650078  0.70480331 0.0104578  1.04608523]
 [0.56437346 0.40396135 0.63479485 0.19800022 0.18712387]
 [0.79749994 1.36396665 0.22879634 1.3151704  0.13828979]
 [0.10048881 0.69521738 0.12743697 0.03412317 0.31376818]]


### sum along a specified axis

In [152]:
arr = np.array([1,5,7,8,11])
arr.ndim , arr.sum()

(1, 32)

In [156]:
arr = np.array([[1,2,9],
                [4,6,5]])

In [157]:
arr 

array([[1, 2, 9],
       [4, 6, 5]])

In [158]:
print(np.sum(arr, axis=0)) # 5 * 5 --> 5 sum    

[ 5  8 14]


In [159]:
print(np.sum(arr, axis=1))    

[12 15]


In [160]:
print(np.sum(arr))

27


In [161]:
arr.sum()

27

### compute the min and max along a specified axis

In [162]:
arr 

array([[1, 2, 9],
       [4, 6, 5]])

In [163]:
# calculate min along the col 
print(np.min(arr, axis=0))

[1 2 5]


In [164]:
print(np.max(arr, axis=1))    

[9 6]


In [165]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

9
1


### compute the indices of the min and max along a specified axis

In [166]:
# important
np.argmin([2,9,7,1])

3

In [167]:
# important
np.argmax([1,2,9,7])

2

### compute element-wise min and max of two arrays

In [154]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[1 4 5 8 9]

[0 3 3 7 7]


### compute the mean

In [168]:
arr  

array([[1, 2, 9],
       [4, 6, 5]])

In [171]:
# compute the overall mean
print(np.mean(arr))

4.5


In [170]:
# compute the mean along the col
print(np.mean(arr, axis=0))   

[2.5 4.  7. ]


In [173]:
# compute the mean along the row
print(np.mean(arr, axis=1)) 

[4. 5.]


In [174]:
arr.mean()

4.5

### compute the median

In [175]:
# compute the overall median
x = np.array([1,2,4,6,7,8,9,12, 20])
print(np.median(x))

7.0


In [176]:
arr 

array([[1, 2, 9],
       [4, 6, 5]])

In [177]:
# compute the median along the column
print(np.median(arr, axis=0)) 

[2.5 4.  7. ]


In [178]:
# compute the median along the row
print(np.median(arr, axis=1))

[2. 5.]


In [179]:
np.median(arr)

4.5

### compute the standard deviation & variance

In [180]:
# compute the overall standard deviation
print(np.std(arr))

2.6299556396765835


In [181]:
# compute the overall variance
print(np.var(arr))

6.916666666666667


In [168]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [169]:
# return an array of bools
print(arr1 == arr2)   

[False False  True False False]


In [170]:
def checkequal(arr1, arr2): 
    x = arr1 == arr2
    for i in x : 
        if i == False:  
            return False 
    return True 

In [171]:
checkequal(arr1 ,  arr2 )

False

In [175]:
arr1 

array([1, 2, 3, 4, 5])

In [176]:
print(arr1 < 3)

[ True  True False False False]


### Reshape

In [182]:
arr = np.array(range(100))
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [183]:
arr.shape 
# 100 value in one row  ( 1, 100 ) , (100, )

(100,)

In [184]:
arr.ndim

1

In [185]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
arr = np.array(range(100)).reshape((50,2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [38]:
arr = np.array(range(100)).reshape((2,50))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [39]:
arr = np.array(range(100)).reshape((4,25))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [186]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
arr.shape

(10, 10)

In [187]:
print(arr[5][5]) # arr[row][col]

# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [188]:
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
arr[ 0 : 2 ] # arr[inclusive : exclusive]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [190]:
arr [ 0 : 2 , 0 : 2 ]

array([[ 0,  1],
       [10, 11]])

In [14]:
print(arr[1:3])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [15]:
print(arr[1:3, :])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [16]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [191]:
arr = np.arange(25).reshape(5,5)
np.random.shuffle(arr)
arr

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [193]:
arr = np.arange(25)
np.random.shuffle(arr)
arr = arr.reshape(5,5)
arr 

array([[ 2, 19, 10,  8, 24],
       [11,  1,  7,  3, 18],
       [21, 22, 23,  5,  4],
       [14, 17, 12,  9,  6],
       [13, 20, 15,  0, 16]])

### sort an array along a specified axis

In [20]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[ 6 10  1  2  0]
 [14 16  3  4  7]
 [15 17 13  5  9]
 [22 19 18  8 11]
 [24 21 20 12 23]]


In [21]:
print(np.sort(arr, axis=1))   

[[ 0  5 14 18 21]
 [ 2 16 20 22 23]
 [ 3  7 12 19 24]
 [ 4  6  9 10 13]
 [ 1  8 11 15 17]]


### Transpose an array

In [22]:
arr = np.array([[6,1], [8,2]])
print(arr)

print()
# the following methods return a copy
print(arr.T)
print()
# or 
print("best")
print(np.transpose(arr)) # best way 
print()
# or
print(arr.transpose())

[[6 1]
 [8 2]]

[[6 8]
 [1 2]]

best
[[6 8]
 [1 2]]

[[6 8]
 [1 2]]


### change the shape of an array

In [194]:
arr = np.random.rand(3,4)
arr

array([[0.82358768, 0.35827327, 0.64230575, 0.34122989],
       [0.01309818, 0.3826047 , 0.43842746, 0.28311805],
       [0.22322571, 0.09173787, 0.59788021, 0.68912149]])

In [196]:
# array : 12  3*4 , 6*2 , 2*3*2
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.82358768, 0.35827327, 0.64230575, 0.34122989, 0.01309818,
        0.3826047 ],
       [0.43842746, 0.28311805, 0.22322571, 0.09173787, 0.59788021,
        0.68912149]])

### flatten an array

In [197]:
arr 

array([[0.82358768, 0.35827327, 0.64230575, 0.34122989],
       [0.01309818, 0.3826047 , 0.43842746, 0.28311805],
       [0.22322571, 0.09173787, 0.59788021, 0.68912149]])

In [89]:
arr.shape

(10, 10)

In [90]:
# important
# return a copy
new = arr.flatten()
print(new)
print(new.shape)
print(new.ndim) # number of dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)
1


In [32]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([3, 4, 4, 2])

### append elements to an array

In [198]:
arr = np.array([1,2,3])

In [199]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [200]:
arr

array([1, 2, 3])

In [193]:
# if I want to delete the old array from memory : del arr 

In [201]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [202]:
arr

array([1, 2, 3])

### insert elements into an array

In [203]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [204]:
arr 

array([1, 2, 3])

In [205]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


In [206]:
arr

array([1, 2, 3])

### delete elements from an array

In [207]:
arr

array([1, 2, 3])

In [208]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [209]:
arr

array([1, 2, 3])

In [210]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


In [211]:
arr

array([1, 2, 3])

In [212]:
arr5 = np.delete(arr, -1)
arr5 

array([1, 2])

In [213]:
arr

array([1, 2, 3])

In [215]:
# where array = 3 
np.where(arr == 3 )

(array([2]),)

In [216]:
array = np.array([1,2,3,3,4,4,5,5,3,3,3])
np.where (array == 3) 

(array([ 2,  3,  8,  9, 10]),)

### copy an array

In [217]:
arr = np.array([1,2,3])

In [218]:
arrx = arr

In [219]:
arrx 

array([1, 2, 3])

In [220]:
arrx[0] = 7

In [221]:
arrx

array([7, 2, 3])

In [222]:
print(arrx) 

[7 2 3]


In [223]:
arr

array([7, 2, 3])

In [224]:
np.info(arr)

class:  ndarray
shape:  (3,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x11380d120
byteorder:  little
byteswap:  False
type: int64


In [225]:
np.info(arrx)

class:  ndarray
shape:  (3,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x11380d120
byteorder:  little
byteswap:  False
type: int64


In [227]:
id(arr)

4660038992

In [229]:
id(arrx)

4660038992

In [230]:
# note in c++: 

int x = 3; 
int y = x ; 
y = 4; 
cout << x << endl; // prints 3 
cout << y << endl; // prints 4 

SyntaxError: invalid syntax (1383131432.py, line 3)

In [231]:
x = 2 

In [232]:
y = 2 

In [233]:
id(x)

4382796112

In [234]:
id(y)

4382796112

In [60]:
y = 3 
id(y) 

140210818050416

In [235]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
a = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

In [236]:
np.info(arr)

class:  ndarray
shape:  (3,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x11380d120
byteorder:  little
byteswap:  False
type: int64


In [237]:
np.info(a)

class:  ndarray
shape:  (3,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x10690a5c0
byteorder:  little
byteswap:  False
type: int64


In [64]:
# in dict : 
new_dict = { "name" : "Ahmed", "age" : 23, "shift" : {"morning" : "4-10", "night": '8-11'} }
dict_2 = new_dict.copy()

In [65]:
id(new_dict)

140210697769664

In [66]:
id(dict_2)

140210697919808

In [67]:
new_dict["shift"]["morning"] = 5 

In [72]:
id(new_dict)

140210697769664

In [73]:
id(dict_2)

140210697919808

In [70]:
new_dict 

{'name': 'Ahmed', 'age': 23, 'shift': {'morning': 5, 'night': '8-11'}}

In [71]:
dict_2

{'name': 'Ahmed', 'age': 23, 'shift': {'morning': 5, 'night': '8-11'}}

In [237]:
# from copy import deepcopy 

### Concatination

In [239]:
arr1 = np.array([[1,2,3,4], 
                 [6,11,33,42]
                ])

arr2 = np.array([[5,6,7,8],
                 [55,63,37,81]
                ])

In [240]:
arr1 

array([[ 1,  2,  3,  4],
       [ 6, 11, 33, 42]])

In [241]:
arr2 

array([[ 5,  6,  7,  8],
       [55, 63, 37, 81]])

In [242]:
arr1.shape

(2, 4)

In [243]:
arr2.shape

(2, 4)

### ```np.concatenate((a, b), axis=0)```

In [244]:
# concat along the row
concat = np.concatenate((arr1, arr2), axis=0)        
print(concat)
print(concat.shape)

[[ 1  2  3  4]
 [ 6 11 33 42]
 [ 5  6  7  8]
 [55 63 37 81]]
(4, 4)


In [245]:
# concat along the column
concat = np.concatenate((arr1, arr2), axis=1)    
print(concat)
print(concat.shape)

[[ 1  2  3  4  5  6  7  8]
 [ 6 11 33 42 55 63 37 81]]
(2, 8)


### Different shapes

In [246]:
arr1 = np.array([[1,2,3,4], [1,25,37,4], [3,4,5,6]])
arr1.shape 

(3, 4)

In [247]:
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr2.shape 

(2, 4)

In [248]:
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
newconcat = np.concatenate((arr1, arr2), axis=0)
print(newconcat)
newconcat.shape 

[[ 1  2  3  4]
 [ 1 25 37  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 5  6  7  8]]


(5, 4)

In [84]:
# columns won't work
arr1 = np.array([[1,2,3,4], [1,2,3,4], [3,4,5,6]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
newconcat = np.concatenate((arr1, arr2), axis=1)
newconcat

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [249]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [250]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [251]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [252]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [253]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### Split an array 

In [254]:
arr = np.random.rand(6,6)
arr

array([[0.22563595, 0.7994659 , 0.69608941, 0.39748466, 0.78777483,
        0.95194086],
       [0.07941867, 0.40884378, 0.58059636, 0.34057299, 0.43054355,
        0.16041506],
       [0.70192578, 0.87695641, 0.49464404, 0.11154016, 0.61988546,
        0.58870565],
       [0.31581356, 0.07065811, 0.12179135, 0.19149589, 0.78313659,
        0.31815345],
       [0.00394698, 0.56544525, 0.01838878, 0.30506123, 0.25423284,
        0.68928204],
       [0.31407754, 0.24558608, 0.33901716, 0.10185624, 0.49246063,
        0.03644215]])

In [86]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(len(arr1))
print(arr1[0].shape)
print(arr1[1].shape)
print(arr1)

#  [] 
# ---- 
#  []

2
(3, 6)
(3, 6)
[array([[0.92164498, 0.21055322, 0.79988019, 0.9569966 , 0.45001725,
        0.80728164],
       [0.52861599, 0.0794147 , 0.51146681, 0.70342674, 0.23983162,
        0.37801683],
       [0.87862107, 0.15722127, 0.11280972, 0.37517718, 0.99141388,
        0.37316236]]), array([[0.02866452, 0.70809226, 0.18987597, 0.47090915, 0.20309178,
        0.37545206],
       [0.19613435, 0.5300827 , 0.8959981 , 0.71683904, 0.01689894,
        0.23396859],
       [0.50591305, 0.6283499 , 0.86201822, 0.83044535, 0.9502819 ,
        0.39107984]])]


In [87]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2[0].shape)
print(arr2[1].shape)
print(arr2)

# [ | ]

(6, 3)
(6, 3)
[array([[0.92164498, 0.21055322, 0.79988019],
       [0.52861599, 0.0794147 , 0.51146681],
       [0.87862107, 0.15722127, 0.11280972],
       [0.02866452, 0.70809226, 0.18987597],
       [0.19613435, 0.5300827 , 0.8959981 ],
       [0.50591305, 0.6283499 , 0.86201822]]), array([[0.9569966 , 0.45001725, 0.80728164],
       [0.70342674, 0.23983162, 0.37801683],
       [0.37517718, 0.99141388, 0.37316236],
       [0.47090915, 0.20309178, 0.37545206],
       [0.71683904, 0.01689894, 0.23396859],
       [0.83044535, 0.9502819 , 0.39107984]])]


In [255]:
arr = np.random.rand(5,3)
arr

array([[0.20141016, 0.60065406, 0.55138844],
       [0.0839947 , 0.42517387, 0.35934421],
       [0.56486858, 0.34493025, 0.66299723],
       [0.81681226, 0.28807652, 0.42135302],
       [0.28816068, 0.1110494 , 0.44536544]])

In [265]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2[0].shape)
print(arr2[1].shape)
print(arr2)

ValueError: array split does not result in an equal division

In [266]:
arr

array([[0.34338074, 0.3194028 , 0.01288289],
       [0.23654646, 0.76361588, 0.46296375],
       [0.71936523, 0.04712842, 0.97897375],
       [0.68816312, 0.61308493, 0.06646768],
       [0.74616619, 0.33241434, 0.54267538]])

In [89]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 3)
print(arr2[0].shape)
print(arr2[1].shape)
print(arr2[2].shape)
print(arr2)

(5, 1)
(5, 1)
(5, 1)
[array([[0.29214702],
       [0.77776432],
       [0.84132645],
       [0.65429521],
       [0.54399642]]), array([[0.73373094],
       [0.82127996],
       [0.87875914],
       [0.31952528],
       [0.32371471]]), array([[0.88239814],
       [0.60394901],
       [0.18866445],
       [0.57282114],
       [0.88082769]])]


### Select the unique elements from an array

In [256]:
arr = np.array([7,1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6 7]


In [257]:
arr = np.array([7,1,1,2,2,3,3,4,5,6,-1])
print(np.unique(arr))

[-1  1  2  3  4  5  6  7]


In [124]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)

#print(type(uniques))
print(uniques)
#print(type(counts))
print(counts)

x = int(counts[0])
type(x)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


int

### compute the intersection & union of two arrays

In [258]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [260]:
# intersection
np.intersect1d(arr1, arr2), type(np.intersect1d(arr1, arr2))

(array([3, 4, 5]), numpy.ndarray)

In [261]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [262]:
arr1 = np.array([4,3,2,1,5])
arr2 = np.array([3,4,5,6,7])
# intersection
print(np.intersect1d(arr1, arr2))
print(type(np.intersect1d(arr1, arr2)))

[3 4 5]
<class 'numpy.ndarray'>


In [98]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [99]:
# index where arr1 == 3 : return index 2 
np.where(arr1 == 3)

(array([2]),)

In [283]:
arr1 = np.array([1,2,3,2,3])
np.where(arr1 == 3)

(array([2, 4]),)

### compute whether each element of an array is contained in another

In [263]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [264]:
arr1 

array([1, 2, 3, 4, 5])

In [265]:
arr2

array([3, 4, 5, 6, 7])

In [131]:
print(np.in1d(arr1, arr2))
# arr1 =  1 , 2, ,3 ,4, 5 
# arr2 = 3, 4, 5 , 6 , 7

[False False  True  True  True]


In [266]:
# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(arr1, arr2))

[False False  True  True  True]


### compute the elements in an array that are not in another

In [267]:
arr1 

array([1, 2, 3, 4, 5])

In [268]:
arr2 

array([3, 4, 5, 6, 7])

In [269]:
print(np.setdiff1d(arr2, arr1))

[6 7]


In [270]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [271]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


### matrix multiplication

In [272]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [273]:
arr1 

array([[0.72677054, 0.25586087, 0.38983243, 0.34312159, 0.47856468],
       [0.56946847, 0.68600079, 0.03940066, 0.97363213, 0.97043983],
       [0.96326904, 0.92624096, 0.02125642, 0.19843173, 0.85005382],
       [0.4986098 , 0.22410541, 0.40166811, 0.01289937, 0.22184741],
       [0.28296552, 0.59400668, 0.10329247, 0.3452721 , 0.58351893]])

In [274]:
arr2 

array([[0.51336444, 0.71147934, 0.89244709, 0.83874845, 0.66919434],
       [0.75011899, 0.91951622, 0.12743164, 0.12491273, 0.66519183],
       [0.04070416, 0.78896157, 0.03288619, 0.13521837, 0.59687673],
       [0.32382047, 0.91751139, 0.61543562, 0.02003856, 0.7176307 ],
       [0.09566469, 0.47440757, 0.20407439, 0.08041879, 0.31694674]])

In [114]:
print(arr1.dot(arr2))
print(arr1.dot(arr2).shape)
# or
print()
print(np.dot(arr1, arr2))
# or
print()
print(arr1 @ arr2)

[[1.07418258 1.02851062 1.54322684 1.06388331 0.69598716]
 [0.76687925 1.1723785  1.01946666 0.31341213 0.38936225]
 [0.75815848 0.66051517 1.21372799 0.82455049 0.59603766]
 [0.75994082 1.07380003 0.89219026 0.46498214 0.43089481]
 [1.02644119 1.0262437  1.49636676 1.06147974 0.71930566]]
(5, 5)

[[1.07418258 1.02851062 1.54322684 1.06388331 0.69598716]
 [0.76687925 1.1723785  1.01946666 0.31341213 0.38936225]
 [0.75815848 0.66051517 1.21372799 0.82455049 0.59603766]
 [0.75994082 1.07380003 0.89219026 0.46498214 0.43089481]
 [1.02644119 1.0262437  1.49636676 1.06147974 0.71930566]]

[[1.07418258 1.02851062 1.54322684 1.06388331 0.69598716]
 [0.76687925 1.1723785  1.01946666 0.31341213 0.38936225]
 [0.75815848 0.66051517 1.21372799 0.82455049 0.59603766]
 [0.75994082 1.07380003 0.89219026 0.46498214 0.43089481]
 [1.02644119 1.0262437  1.49636676 1.06147974 0.71930566]]


In [275]:
arr1 = np.random.rand(2,5)
arr2 = np.random.rand(5,4)

In [276]:
print(arr1.dot(arr2))
print(arr1.dot(arr2).shape)

[[1.36373317 1.78887506 1.06139317 1.27665373]
 [1.01409861 1.34698322 0.97302396 1.15410797]]
(2, 4)


### Save Numpy array into a file 

In [277]:
x = np.arange(10)
y = x ** 2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [278]:
np.savez("x_y-squared.npz", x_axis=x, y_axis=y)

In [279]:
del x, y

In [280]:
load_xy = np.load("x_y-squared.npz")
print(load_xy.files)

['x_axis', 'y_axis']


In [281]:
x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [282]:
a = np.array([1, 2, 3, 4])
np.savetxt('array.txt', a, fmt='%d')
b = np.loadtxt('array.txt', dtype=int)

In [283]:
b 

array([1, 2, 3, 4])

In [284]:
a 

array([1, 2, 3, 4])

In [285]:
a.tofile('test2.dat') # data file 
c = np.fromfile('test2.dat', dtype=int)

In [286]:
c

array([1, 2, 3, 4])

In [287]:
np.save('data.npy', a) # save
new_num_arr = np.load('data.npy') # load

In [288]:
new_num_arr

array([1, 2, 3, 4])

__Practice:__ https://www.w3resource.com/python-exercises/numpy/index.php

Further readings if you are interested:
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.byteorder.html
- https://en.wikipedia.org/wiki/Endianness