In [1]:
import numpy as np

In [8]:
np.random.rand(3)

array([0.35963573, 0.00088364, 0.31297876])

### set seed

In [11]:
np.random.seed(11)
np.random.rand(4)

array([0.18026969, 0.01947524, 0.46321853, 0.72493393])

In [13]:
np.random.seed(24)
np.random.rand(4)

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 ])

In [23]:
np.random.seed(2)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

In [17]:
np.random.seed()
np.random.rand(3)

array([0.61793663, 0.20843386, 0.43295107])

### set random state which is independent from the global seed

In [18]:
rs = np.random.RandomState(23)
rs.rand(10)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009])

In [19]:
rs = np.random.RandomState(321)
rs.rand(3)

array([0.88594794, 0.07791236, 0.97964616])

### generate a random sample from interval [0, 1) in a given shape

In [20]:
# generate a random scalar
print(np.random.rand())  # from zero to one    

0.024044499702882027


In [26]:
# generate a random scalar
print(np.random.rand() * 10)      

5.874460193902271


In [40]:
# generate a random scalar
print(int(np.random.rand() * 10))      

9


In [41]:
# generate a random scalar
print(np.random.rand() * 100) 

27.223346466106257


In [42]:
# generate a 1-D array
print(np.random.rand(10) )
print(type(np.random.rand(10)))

[0.22456582 0.68769771 0.696884   0.26011898 0.11567299 0.84329806
 0.09095187 0.59753172 0.14320772 0.4802155 ]
<class 'numpy.ndarray'>


In [49]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.17247019 0.45174701 0.74062223]
 [0.97136114 0.52720777 0.55699105]
 [0.92465324 0.76727437 0.98284087]]


In [50]:
# generate a 3-D array
print(np.random.rand(3,3,3))

[[[0.23513604 0.93426901 0.96895982]
  [0.07919516 0.12789201 0.45337421]
  [0.34408523 0.76019192 0.58901476]]

 [[0.00539354 0.47589813 0.7964832 ]
  [0.10420795 0.24910918 0.78450449]
  [0.66512207 0.95574964 0.6538948 ]]

 [[0.74871253 0.27863491 0.90973687]
  [0.39839548 0.13802214 0.73210574]
  [0.15155034 0.85247348 0.68158296]]]


In [51]:
# generate a 4-D array
print(np.random.rand(3,3,3,3))          

[[[[0.11671312 0.63510645 0.08810672]
   [0.11434707 0.03883425 0.30872273]
   [0.16878903 0.37168561 0.45212367]]

  [[0.95256138 0.18043605 0.10675846]
   [0.84128331 0.15443547 0.2930486 ]
   [0.77913723 0.20414614 0.33702618]]

  [[0.81971967 0.4678776  0.04870457]
   [0.41714334 0.34242929 0.44025595]
   [0.15058006 0.13671488 0.95622702]]]


 [[[0.03448106 0.24935597 0.76673477]
   [0.11811586 0.91786095 0.76576592]
   [0.35577298 0.16143678 0.97468245]]

  [[0.91871395 0.91549115 0.86509457]
   [0.82994045 0.24206757 0.94317587]
   [0.58258093 0.42254068 0.56256585]]

  [[0.38200027 0.7101625  0.20541306]
   [0.37731373 0.48737547 0.33094414]
   [0.72224743 0.45138564 0.53746179]]]


 [[[0.72084691 0.52799708 0.60075724]
   [0.82400871 0.73745542 0.17903031]
   [0.04543453 0.18159754 0.62113347]]

  [[0.68459944 0.14944016 0.17881647]
   [0.98955512 0.30515051 0.45047413]
   [0.2174438  0.67162808 0.46618019]]

  [[0.58585164 0.75174003 0.07447219]
   [0.18319278 0.90520872 0.85

### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [52]:
print(np.random.randn(3,3))

[[-1.42164296  0.07920723  3.02208838]
 [ 0.63570214 -0.88908011  0.89313544]
 [-0.59754319 -0.05249684  0.8893473 ]]


### generate an array of random integers in a given interval [low, high)

In [59]:
# np.ranodm.ran|dint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[1 5 1]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [50]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print()
print(np.random.random(10))
print()
print(np.random.ranf(10))
print()
print(np.random.sample(10))

[0.73535139 0.18558973 0.13209176 0.00997191 0.37304105 0.01080092
 0.84846201 0.24316678 0.68002726 0.67713974]

[0.88582741 0.15356567 0.94669413 0.29374373 0.73660054 0.47553897
 0.16486714 0.82745335 0.5396978  0.35417242]

[0.84199769 0.03180488 0.06773524 0.62818122 0.63494351 0.76973697
 0.44138863 0.85846834 0.38166258 0.96478065]

[0.78030187 0.42597475 0.34609815 0.53918262 0.43121391 0.78263302
 0.66732717 0.69261888 0.3438399  0.575779  ]


### generate a random sample from a given 1-D array

In [65]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.3, 0.6]))

[2 2 2 2 1 1 2 2 2 1]


In [88]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.4, 0.4, 0.2]))

[1 2 2 1 1 1 1 0 1 2]


In [89]:
print(np.random.choice(3, 10))

[0 2 2 0 1 2 0 0 0 1]


In [64]:
print(np.random.choice([1,2,3], 10))

[3 2 1 2 3 2 2 2 3 3]


### shuffle an array in place

In [60]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
np.random.shuffle(arr)
print(arr)

[7 8 0 6 5 3 4 2 9 1]


### generate a permutation of an array

In [70]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [6 1 5 8 4 3 9 0 7 2]
