In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)
arr

array([[0.08703721, 0.16898792, 0.97826852, 0.95605285, 0.5958411 ],
       [0.74206773, 0.89693649, 0.80942644, 0.30465311, 0.58424691],
       [0.24621048, 0.85367366, 0.83207619, 0.71764329, 0.69413535],
       [0.69226755, 0.61429797, 0.59026868, 0.84675188, 0.25813614],
       [0.51342042, 0.90320273, 0.89222036, 0.90242758, 0.28357091]])

### element-wise addition, subtraction, multiplication and division

In [3]:
print(arr + 10)
print()
print(arr - 10)
print()
print(arr * 10)
print()
print(arr / 10)

[[10.08703721 10.16898792 10.97826852 10.95605285 10.5958411 ]
 [10.74206773 10.89693649 10.80942644 10.30465311 10.58424691]
 [10.24621048 10.85367366 10.83207619 10.71764329 10.69413535]
 [10.69226755 10.61429797 10.59026868 10.84675188 10.25813614]
 [10.51342042 10.90320273 10.89222036 10.90242758 10.28357091]]

[[-9.91296279 -9.83101208 -9.02173148 -9.04394715 -9.4041589 ]
 [-9.25793227 -9.10306351 -9.19057356 -9.69534689 -9.41575309]
 [-9.75378952 -9.14632634 -9.16792381 -9.28235671 -9.30586465]
 [-9.30773245 -9.38570203 -9.40973132 -9.15324812 -9.74186386]
 [-9.48657958 -9.09679727 -9.10777964 -9.09757242 -9.71642909]]

[[0.87037205 1.68987925 9.78268516 9.56052846 5.958411  ]
 [7.42067734 8.96936486 8.09426438 3.04653112 5.84246908]
 [2.46210483 8.53673655 8.32076193 7.17643287 6.94135351]
 [6.92267553 6.14297969 5.90268682 8.46751882 2.58136135]
 [5.13420423 9.0320273  8.92220358 9.02427584 2.83570909]]

[[0.00870372 0.01689879 0.09782685 0.09560528 0.05958411]
 [0.07420677 0.0

In [4]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
x = np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [2,1,12], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[ 7 10  1]
[ 7 20  3]


### element-wise exponentiation

In [5]:
print(np.exp(arr))

[[1.09093727 1.18410584 2.65984677 2.60140802 1.81455653]
 [2.10027383 2.45207961 2.24661904 1.35615449 1.7936397 ]
 [1.27916879 2.34825771 2.29808506 2.0495972  2.00197732]
 [1.99824152 1.84835854 1.80447318 2.33205973 1.29451504]
 [1.67099695 2.46749318 2.44054252 2.46558126 1.32786303]]


### element-wise logorithm

In [6]:
# natural log ( base e )
print(np.log(arr)) 

[[-2.4414196  -1.77792802 -0.02197109 -0.04494209 -0.51778126]
 [-0.29831475 -0.10877023 -0.21142938 -1.18858149 -0.5374316 ]
 [-1.40156849 -0.15820629 -0.18383126 -0.33178265 -0.36508831]
 [-0.36778276 -0.48727518 -0.52717745 -0.16634756 -1.35426818]
 [-0.66666023 -0.10180824 -0.11404214 -0.10266683 -1.26029307]]


In [7]:
# base 2
print(np.log2(arr))     

[[-3.52222395 -2.56500793 -0.03169758 -0.06483773 -0.74700045]
 [-0.43037722 -0.15692227 -0.30502812 -1.71476062 -0.7753499 ]
 [-2.0220359  -0.22824344 -0.26521245 -0.47866118 -0.52671109]
 [-0.53059836 -0.70298948 -0.7605563  -0.23998881 -1.95379598]
 [-0.96178741 -0.14687825 -0.16452803 -0.14811693 -1.81821856]]


In [8]:
# base 10
print(np.log10(arr))    

[[-1.06029506 -0.77214433 -0.00954192 -0.0195181  -0.22486954]
 [-0.12955645 -0.04723831 -0.09182261 -0.51619438 -0.23340358]
 [-0.60869346 -0.06870812 -0.0798369  -0.14409137 -0.15855584]
 [-0.15972602 -0.21162092 -0.22895026 -0.07224383 -0.5881512 ]
 [-0.28952686 -0.04421476 -0.04952787 -0.04458764 -0.54733833]]


### element-wise square root

In [9]:
print(np.sqrt(arr))

[[0.29502069 0.41108141 0.98907458 0.97777955 0.77190744]
 [0.86143353 0.94706731 0.8996813  0.5519539  0.76436046]
 [0.49619601 0.92394462 0.91218211 0.84713829 0.83314786]
 [0.83202617 0.78377163 0.76828945 0.92019122 0.50807099]
 [0.71653362 0.95036979 0.94457417 0.94996189 0.53251376]]


### element-wise sine and cosine

In [10]:
print(np.sin(arr))

[[0.08692736 0.16818478 0.82953165 0.81692142 0.56120511]
 [0.67581343 0.78141893 0.72389159 0.29996228 0.55157136]
 [0.24373048 0.75369988 0.73933095 0.65761105 0.6397211 ]
 [0.63828439 0.57638498 0.55658426 0.74913274 0.25527889]
 [0.49115954 0.78531374 0.77846735 0.78483361 0.27978572]]


In [11]:
print(np.cos(arr))

[[0.99621465 0.98575549 0.5584597  0.57674899 0.82767676]
 [0.73707273 0.62400678 0.68991374 0.95395106 0.83412771]
 [0.969843   0.65721875 0.67334222 0.75335762 0.76860712]
 [0.76980065 0.81717829 0.83079117 0.66241991 0.96686746]
 [0.87106963 0.619098   0.6276851  0.61970655 0.96006247]]


In [12]:
x = np.array([  [1,3]  , [2,5 ]])
print(x.sum(axis = 0))
print(x.sum(axis = 1 ))

[3 8]
[4 7]


### sum along a specified axis

In [13]:
# sum along the row
print(np.sum(arr, axis=0)) # 5 * 5 --> 5 sum    

[2.2810034  3.43709876 4.10226019 3.72752871 2.4159304 ]


In [13]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.84917508 2.04907024 2.73647456 1.92595012 2.21357959]


In [14]:
print(np.sum(arr))

15.963821465909003


### compute the min and max along a specified axis

In [15]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.08703721 0.16898792 0.59026868 0.30465311 0.25813614]


In [16]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.97826852 0.89693649 0.85367366 0.84675188 0.90320273]


In [17]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9782685164239541
0.08703720545074634


### compute the indices of the min and max along a specified axis

In [18]:
arr

array([[0.74446616, 0.16456029, 0.21774863, 0.88996122, 0.83243878],
       [0.3494273 , 0.09871643, 0.83174332, 0.43746475, 0.33171843],
       [0.48834284, 0.63369739, 0.97726446, 0.51289937, 0.1242705 ],
       [0.31228128, 0.52937954, 0.05819263, 0.32381417, 0.7022825 ],
       [0.59156342, 0.31363578, 0.42084753, 0.36868838, 0.51884449]])

In [18]:
np.argmin([1,2,9,7])

0

In [20]:
np.argmax([1,2,9,7])

2

In [19]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[3 1 3 3 2]
[0 2 2 0 0]


In [22]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[2 1 4 4 1]
[1 0 3 2 0]


In [20]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

17
12


In [21]:
arr

array([[0.74446616, 0.16456029, 0.21774863, 0.88996122, 0.83243878],
       [0.3494273 , 0.09871643, 0.83174332, 0.43746475, 0.33171843],
       [0.48834284, 0.63369739, 0.97726446, 0.51289937, 0.1242705 ],
       [0.31228128, 0.52937954, 0.05819263, 0.32381417, 0.7022825 ],
       [0.59156342, 0.31363578, 0.42084753, 0.36868838, 0.51884449]])

### compute element-wise min and max of two arrays

In [22]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[1 4 5 8 9]

[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [26]:
print(20 / 3)
x = 20/3
x = str(x)
print(x.split("."))
anas = x.split(".")[1]
print(f"fraction = {anas}")
x = int(x[2:])

print(x)
print (20 // 3)

6.666666666666667
['6', '666666666666667']
fraction = 666666666666667
666666666666667
6


In [27]:
y= ((20/3)-(20 // 3))
print(y)
x = (len(str((20/3)-(20 // 3)))-2)
print(int((10**x) * y))

0.666666666666667
666666666666667


In [28]:
20 % 3

2

In [22]:
arr1 = np.random.rand(10) * 10

print(arr1)
print()
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

[9.50628875 0.38150436 5.14659478 4.86866046 7.11195495 5.00143839
 8.34814286 2.45064772 0.46030561 0.03324892]

fractional:  [0.50628875 0.38150436 0.14659478 0.86866046 0.11195495 0.00143839
 0.34814286 0.45064772 0.46030561 0.03324892]
integral:  [9. 0. 5. 4. 7. 5. 8. 2. 0. 0.]


In [24]:
newarr = np.array([1.23,])
re , intg  = np.modf(newarr)

# rounding the number to get the accurate reuslt
fraction = round(float(re), 2)
integer = int(intg)
print(fraction)
print(integer)

0.23
1


### compute the mean

In [23]:
# compute the overall mean
print(np.mean(arr))

0.6385528586363601


In [24]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.45620068 0.68741975 0.82045204 0.74550574 0.48318608]


In [25]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.55723752 0.66746614 0.66874779 0.60034444 0.6989684 ]


### compute the median

In [26]:
# compute the overall median
x = [1,2,4,6,7,8,9,12, 20]
print(np.median(x))

7.0


In [28]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.51342042 0.85367366 0.83207619 0.84675188 0.58424691]


In [29]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.5958411  0.74206773 0.71764329 0.61429797 0.89222036]


### compute the percentile

In [29]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.0458976  0.57877554 0.96232918]


### compute the standard deviation & variance

In [30]:
# compute the overall standard deviation
print(np.std(arr))

0.2646032851663963


In [31]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.25341633 0.28007794 0.12907191 0.23423607 0.17770635]


In [32]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.37673255 0.20829474 0.220203   0.19316792 0.25590496]


In [33]:
# compute the overall variance
print(np.var(arr))

0.07001489852084924


In [34]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.06421984 0.07844365 0.01665956 0.05486654 0.03157955]


In [35]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.14192742 0.0433867  0.04848936 0.03731385 0.06548735]


### compute the covariance & correlation

In [36]:
arr = np.random.rand(5,8)
arr

array([[0.82846544, 0.64744212, 0.62507761, 0.06063646, 0.09181703,
        0.87952103, 0.57149992, 0.16866836],
       [0.74779433, 0.40463146, 0.22884716, 0.63409602, 0.92762708,
        0.23665169, 0.08431273, 0.11654295],
       [0.3940467 , 0.50918354, 0.03673743, 0.09968312, 0.31599352,
        0.86195505, 0.13074781, 0.41189045],
       [0.77554296, 0.6315781 , 0.15528698, 0.07856415, 0.48119019,
        0.69025572, 0.98319062, 0.60737834],
       [0.14378358, 0.24417093, 0.54600707, 0.07835408, 0.47910438,
        0.16231102, 0.91500076, 0.6954784 ]])

In [38]:
print(np.cov(arr))

[[ 0.07787956 -0.05859352 -0.01568495  0.02379198 -0.0192686 ]
 [-0.05859352  0.08709431  0.01986174 -0.02692695  0.02960537]
 [-0.01568495  0.01986174  0.08849349 -0.05014816 -0.03347827]
 [ 0.02379198 -0.02692695 -0.05014816  0.09674184  0.00563515]
 [-0.0192686   0.02960537 -0.03347827  0.00563515  0.11446072]]


In [39]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.13494411]
 [-0.13494411  1.        ]]


### compute cumulative sum & product

In [38]:
       1 3 5 6 8 9
csum = 1 4 9 15 23 32
cpro = 1 3 15 90 720 6480 

SyntaxError: invalid syntax (2474441132.py, line 1)

In [39]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.82846544 0.64744212 0.62507761 0.06063646 0.09181703 0.87952103
  0.57149992 0.16866836]
 [1.57625977 1.05207358 0.85392477 0.69473248 1.01944411 1.11617273
  0.65581264 0.28521131]
 [1.97030647 1.56125713 0.89066221 0.79441561 1.33543763 1.97812778
  0.78656045 0.69710176]
 [2.74584943 2.19283523 1.04594919 0.87297976 1.81662781 2.6683835
  1.76975107 1.3044801 ]
 [2.88963301 2.43700615 1.59195626 0.95133384 2.2957322  2.83069451
  2.68475182 1.99995851]]


In [39]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.07699789 0.60620165 1.38113585 2.26368041 2.9387472  3.51619882
  3.6165226  4.19676926]
 [0.51647637 0.76899973 1.45276614 1.51293005 2.27033626 2.44664277
  3.12681191 3.22371123]
 [0.50638659 0.89796037 1.82042495 2.27004012 2.84294979 3.04535231
  3.62439609 3.63802571]
 [0.36486965 1.05222312 1.95701205 2.06161987 2.2134452  2.55087891
  3.11802447 3.29548439]
 [0.45953584 1.15900999 1.89258064 2.38941647 3.16998304 3.94801629
  4.76803737 5.18861841]]


In [40]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[8.28465437e-01 6.47442123e-01 6.25077612e-01 6.06364643e-02
  9.18170277e-02 8.79521034e-01 5.71499918e-01 1.68668358e-01]
 [6.19521760e-01 2.61975452e-01 1.43047237e-01 3.84493406e-02
  8.51719614e-02 2.08140142e-01 4.81847159e-02 1.96571078e-02]
 [2.44120506e-01 1.33393588e-01 5.25518841e-03 3.83275034e-03
  2.69137878e-02 1.79407447e-01 6.30004585e-03 8.09657502e-03]
 [1.89325939e-01 8.42484694e-02 8.16062361e-04 3.01116769e-04
  1.29506506e-02 1.23837016e-01 6.19414596e-03 4.91768432e-03]
 [2.72219618e-02 2.05710268e-02 4.45575818e-04 2.35937278e-05
  6.20471344e-03 2.01001118e-02 5.66764824e-03 3.42014324e-03]]


In [41]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[7.69978878e-02 4.07475720e-02 3.15766872e-02 2.78678334e-02
  1.88126489e-02 1.08633946e-02 1.08985675e-03 6.32385739e-04]
 [5.16476375e-01 1.30422346e-01 8.91784193e-02 5.36532299e-03
  4.06372891e-03 7.16461884e-04 4.87315259e-04 4.72205193e-05]
 [5.06386594e-01 1.98287709e-01 1.82913390e-01 8.22406342e-02
  4.71164550e-02 9.53648907e-03 5.52204469e-03 7.52633727e-05]
 [3.64869647e-01 2.50794419e-01 2.26916013e-01 2.37371911e-02
  3.60390686e-03 1.21607966e-03 6.89694176e-04 1.22393071e-04]
 [4.59535838e-01 3.21433439e-01 2.35794138e-01 1.17150975e-01
  9.14441359e-02 7.11465780e-02 5.83416937e-02 2.45374102e-02]]


### element-wise comparison

In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [10]:
# return an array of bools
print(arr1 == arr2)   

[False False  True False False]


In [11]:
print(arr1 < 3)

[ True  True False False False]
