In [1]:
import numpy as np

In [2]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [4]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [5]:
print(arr[1:3, :])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [6]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [4]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(4,2,2)
print(arr)
print("----------------------")
# equivalent to arr[0,:,:,:]
print(arr[0, ...])
print("----------------------")
print(arr[2:,:,:])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
----------------------
[[0 1]
 [2 3]]
----------------------
[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


### assign a scalar to a slice by broadcasting

In [7]:
arr[1:3,:] = 10    # or simply arr[1:3]
arr[:,1:] = 100
print(arr)

[[  0 100 100 100 100 100 100 100 100 100]
 [ 10 100 100 100 100 100 100 100 100 100]
 [ 10 100 100 100 100 100 100 100 100 100]
 [ 30 100 100 100 100 100 100 100 100 100]
 [ 40 100 100 100 100 100 100 100 100 100]
 [ 50 100 100 100 100 100 100 100 100 100]
 [ 60 100 100 100 100 100 100 100 100 100]
 [ 70 100 100 100 100 100 100 100 100 100]
 [ 80 100 100 100 100 100 100 100 100 100]
 [ 90 100 100 100 100 100 100 100 100 100]]


### boolean indexing

In [9]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
print("----------------------------")
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
----------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [10]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [11]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [12]:
arr = np.random.rand(10,10)
arr

array([[0.71531902, 0.06477467, 0.4294403 , 0.06546486, 0.87836874,
        0.12927867, 0.49253249, 0.53480205, 0.57794732, 0.17309061],
       [0.77693639, 0.59086637, 0.79419145, 0.60864198, 0.86090897,
        0.90690312, 0.15429398, 0.29585644, 0.94981195, 0.36404381],
       [0.71042777, 0.97890937, 0.17779008, 0.78416275, 0.70880141,
        0.90887487, 0.53988935, 0.67029791, 0.70385405, 0.08807391],
       [0.04097259, 0.41642522, 0.91801697, 0.2778399 , 0.20867356,
        0.70955465, 0.88229768, 0.16988325, 0.05812767, 0.66248101],
       [0.37067751, 0.72178174, 0.86760864, 0.93651148, 0.94197312,
        0.45764798, 0.59194158, 0.54391794, 0.32748018, 0.84571478],
       [0.83400799, 0.26476546, 0.0069168 , 0.67451707, 0.53992156,
        0.80604993, 0.28776826, 0.20366441, 0.56724484, 0.52594465],
       [0.07560401, 0.3886899 , 0.69663972, 0.24352058, 0.24541115,
        0.39126948, 0.08093536, 0.36860314, 0.04338731, 0.83354345],
       [0.07453747, 0.72096283, 0.5427379

In [13]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.2778399  0.79419145 0.97890937]


In [12]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.09566854 0.2190723  0.6754328 ]
 [0.28997889 0.13675444 0.07718654]
 [0.15862308 0.45510309 0.94789792]]


### dimension inference

In [13]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [14]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
# find the elements greater than 5 and return a flattened array
print(arr[x : lambda (x > 5) for x in arr])    # or arr[np.where(arr>5)]

SyntaxError: invalid syntax (3141513503.py, line 2)

In [28]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
print(np.where(arr>5))

(array([1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))


In [30]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [8]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
