In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,4)
arr

array([[0.22192227, 0.12387046, 0.03752328, 0.66854367],
       [0.37375627, 0.94266542, 0.13651861, 0.19139346],
       [0.15670052, 0.00149704, 0.36487319, 0.70744997]])

### transpose an array

In [3]:
# the following methods return a copy
print(arr.T)
print()
# or 
print("best")
print(np.transpose(arr)) # best way 
print()
# or
print(arr.transpose())

[[0.22192227 0.37375627 0.15670052]
 [0.12387046 0.94266542 0.00149704]
 [0.03752328 0.13651861 0.36487319]
 [0.66854367 0.19139346 0.70744997]]

best
[[0.22192227 0.37375627 0.15670052]
 [0.12387046 0.94266542 0.00149704]
 [0.03752328 0.13651861 0.36487319]
 [0.66854367 0.19139346 0.70744997]]

[[0.22192227 0.37375627 0.15670052]
 [0.12387046 0.94266542 0.00149704]
 [0.03752328 0.13651861 0.36487319]
 [0.66854367 0.19139346 0.70744997]]


### transpose of a high dimensional array with specified order of axes

In [6]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

print("-------------------------")
arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
-------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [7]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [4]:
#array : 16 --> 4*4 , 8*2 , 2*4*2
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.99609664, 0.7278985 , 0.3439951 , 0.50535521, 0.49805311,
        0.72873483],
       [0.47509832, 0.39562105, 0.26299104, 0.3415756 , 0.30028831,
        0.28899458]])

In [14]:
# arr = [1,2,3] resize(2) -- > 1,2 
# arr = [[2,4,7 ] , [6,4,1 ] ] --> resize --> 2,2 --> [2,4] , [6,4 ]
# change the shape of an array in place
arr.resize((2,6))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### flatten an array

In [4]:
# return a copy
new = arr.flatten()
new.ndim # number of dimensions

1

In [5]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.30079557, 0.11169939, 0.02524211, 0.15474378, 0.03971696,
       0.02848302, 0.97532502, 0.37313172, 0.43805393, 0.11823172,
       0.22747398, 0.7491793 ])

### append elements to an array

In [4]:
arr = np.array([1,2,3])

In [8]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [5]:
arr

array([1, 2, 3])

In [6]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [7]:
arr

array([1, 2, 3])

### insert elements into an array

In [8]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [9]:
arr 

array([1, 2, 3])

In [10]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


In [11]:
arr

array([1, 2, 3])

In [16]:
newarr = np.array([1,3,4])
newarr = np.insert(newarr,0, 5)
newarr

array([5, 1, 3, 4])

In [17]:
arr 

array([1, 2, 3])

### delete elements from an array

In [12]:
arr

array([1, 2, 3])

In [13]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [14]:
arr

array([1, 2, 3])

In [15]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


In [16]:
arr

array([1, 2, 3])

In [17]:
arr5 = np.delete(arr, -1)
arr5 

array([1, 2])

In [18]:
arr

array([1, 2, 3])

### copy an array

In [19]:
arr = np.array([1,2,3])

In [20]:
arrx = arr

In [21]:
arrx 

array([1, 2, 3])

In [22]:
arrx[0] = 7

In [23]:
arrx

array([7, 2, 3])

In [24]:
arr

array([7, 2, 3])

In [ ]:
#note in c++: 

int x = 3; 
int y = x ; 
y = 4; 
cout << x << endl; // print 3 
cout << y << endl; // print 4 

# python (numpy ), same in pandas 

In [25]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
a = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

In [4]:
x = 2 
y = x 
x = 3 
y 

2