In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])


arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [3]:
arr1 

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [4]:
arr2 

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [5]:
arr1.shape

(2, 4)

In [6]:
arr2.shape

(2, 4)

### ```np.concatenate((a, b), axis=0)```

In [7]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [8]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### Different shapes

In [9]:
arr1 = np.array([[1,2,3,4], [1,2,3,4], [3,4,5,6]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
newconcat = np.concatenate((arr1, arr2), axis=0)
newconcat

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [10]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [11]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [12]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [13]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [14]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [15]:
arr = np.random.rand(6,6)
arr

array([[0.81273486, 0.434293  , 0.87235423, 0.57776927, 0.58773003,
        0.24499734],
       [0.1966027 , 0.71503081, 0.72197283, 0.51318816, 0.19908825,
        0.15251443],
       [0.13220131, 0.13224467, 0.9030905 , 0.98967022, 0.43325251,
        0.45075536],
       [0.19717555, 0.90023616, 0.39642461, 0.91138405, 0.18866451,
        0.45129945],
       [0.44242615, 0.50481919, 0.47132626, 0.39425898, 0.98647992,
        0.08638545],
       [0.62507788, 0.78352246, 0.36356841, 0.55873146, 0.90143959,
        0.82283858]])

In [16]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(len(arr1))
print(arr1[0].shape)
print(arr1[1].shape)
print(arr1)

2
(3, 6)
(3, 6)
[array([[0.81273486, 0.434293  , 0.87235423, 0.57776927, 0.58773003,
        0.24499734],
       [0.1966027 , 0.71503081, 0.72197283, 0.51318816, 0.19908825,
        0.15251443],
       [0.13220131, 0.13224467, 0.9030905 , 0.98967022, 0.43325251,
        0.45075536]]), array([[0.19717555, 0.90023616, 0.39642461, 0.91138405, 0.18866451,
        0.45129945],
       [0.44242615, 0.50481919, 0.47132626, 0.39425898, 0.98647992,
        0.08638545],
       [0.62507788, 0.78352246, 0.36356841, 0.55873146, 0.90143959,
        0.82283858]])]


In [17]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2[0].shape)
print(arr2[1].shape)
print(arr2)

(6, 3)
(6, 3)
[array([[0.81273486, 0.434293  , 0.87235423],
       [0.1966027 , 0.71503081, 0.72197283],
       [0.13220131, 0.13224467, 0.9030905 ],
       [0.19717555, 0.90023616, 0.39642461],
       [0.44242615, 0.50481919, 0.47132626],
       [0.62507788, 0.78352246, 0.36356841]]), array([[0.57776927, 0.58773003, 0.24499734],
       [0.51318816, 0.19908825, 0.15251443],
       [0.98967022, 0.43325251, 0.45075536],
       [0.91138405, 0.18866451, 0.45129945],
       [0.39425898, 0.98647992, 0.08638545],
       [0.55873146, 0.90143959, 0.82283858]])]
